Feat/filter tasks by status
niaYaro/RP pull request #9
Opened 2022-12-14 15:48 UTC by niaYaro

2022-12-18 11:00 UTC, vitrovyi requested changes

2022-12-18 11:00 UTC, vitrovyi commented on js/show-options.js
> +changeDataButtons.forEach(activeButton => activeButton.addEventListener('click', saveData));
@niaYaro
Please refactor the code in the whole file.
Now you are using a lot of selectors and listeners. This is not good.
Please cover your inputs by

tag.
And get your input values from the FormData object.
Then manipulate with gathered data.
Some useful links:
https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData
https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects
https://code-boxx.com/get-html-form-data-javascript/

2022-12-21 17:01 UTC, vitrovyi commented on js/checkbox.js
> +    console.log('currentelement', currentElement)
@niaYaro 
you forget this one )

2022-12-21 17:02 UTC, vitrovyi commented on js/new-cycle.js
> +    console.log('tasks', tasks)
remove logs in this file

2022-12-21 17:03 UTC, vitrovyi commented on js/planning-cycle.js
> +    // console.log('get', localStorage.getItem("allTasks"));
remove commented code

2022-12-21 17:21 UTC, vitrovyi commented on js/save-data.js
> +    tasks = savedData;
@niaYaro
We have bug here. If user don't have data in localStorage he can not render tasks.

Please refactore this:
```    if (tasks && tasks.length > 0) {
        taskContainer.innerHTML = '';
        renderTast(tasks);
    }```

2022-12-21 17:28 UTC, vitrovyi commented on js/show-options-draft.js
> +    function showPopUp(event) {
Please add empty lines between functions and other code.

2022-12-21 17:28 UTC, vitrovyi requested changes
Good job!
Please go through comments and make small changes.

2022-12-23 15:13 UTC, niaYaro commented on js/show-options.js
> +changeDataButtons.forEach(activeButton => activeButton.addEventListener('click', saveData));
done

2022-12-23 15:13 UTC, niaYaro commented on js/checkbox.js
> +    console.log('currentelement', currentElement)
done

2022-12-23 15:14 UTC, niaYaro commented on js/new-cycle.js
> +    console.log('tasks', tasks)
done

2022-12-23 15:14 UTC, niaYaro commented on js/planning-cycle.js
> +    // console.log('get', localStorage.getItem("allTasks"));
removed

2022-12-23 15:15 UTC, niaYaro commented on js/save-data.js
> +    tasks = savedData;
done

2022-12-23 15:15 UTC, niaYaro commented on js/show-options-draft.js
> +    function showPopUp(event) {
added empty lines between functions

2022-12-23 15:17 UTC, niaYaro commented
Made correction guided with your comments

2022-12-24 14:23 UTC, vitrovyi approved these changes
@niaYaro 
Good job!
You can merge!

2022-12-25 08:43 UTC, merged